# See https://houndci.com/configuration for help.
haml:
  enabled: true
javascript:
  enabled: true
ruby:
  config_file: .rubocop.yml
  enabled: true
scss:
  config_file: .scss-lint.yml
  enabled: true
