# See https://houndci.com/configuration for help.
haml:
  enabled: true

jshint:
  enabled: true

coffeescript:
  enabled: true

ruby:
  config_file: .rubocop.yml
  enabled: true

scss:
  config_file: .scss-lint.yml
  enabled: true
